spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-data-jpa-pro
    username: root
    password: springheaven
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
